#!/bin/bash
#SBATCH --partition=main
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --mem=10G
#SBATCH --time=1:00:00
#SBATCH --output=/home/mila/g/gillonco/scratch/dpc_%j.txt


# 1. Set directory in which to save results (also update output directory above)
SAVE_DIR=/home/mila/g/gillonco/scratch

if [[ ! -d $SAVE_DIR ]]; then
    echo -e "Save directory '$SAVE_DIR' does not exist. Please set SAVE_DIR to the path of an existing directory."
    exit 1
fi


# 2. Load modules
module purge
module load anaconda/3
module load cuda/10.2/cudnn/7.6

conda activate ssl


# 3. Set fixed hyperparameters
SE=5
N_SEQ=4
PE=0.1
SEED=2


# 4. Results are saved in $SLURM_TMPDIR
EXIT=0

cd dpc

set -x # echo commands to console

python test_gabors.py \
    --save_dir $SLURM_TMPDIR \
    --gpu 0 \
    --net resnet18 \
    --dataset gabors \
    --batch_size 10 \
    --img_dim 128 \
    --train_what ft \
    --epochs 25 \
    --unexpected_epoch 5 \
    --pred_step 1 \
    --print_freq 1 \
    --roll 'True' \
    --seq_len $SE \
    --num_seq $N_SEQ \
    --U_prob $PE \
    --seed $SEED \

code="$?"
if [ "$code" -gt "$EXIT" ]; then EXIT="$code"; fi # collect exit code

set +x # stop echoing commands to console

# 5. Copy results and model to SAVE_DIR
cd $SLURM_TMPDIR
LOCAL_DIR=$SAVE_DIR/test_gabors/not-pretrained
mkdir -p $LOCAL_DIR
find . -type f -name "*.json" | cpio -pdm $LOCAL_DIR
cp -r log* $LOCAL_DIR

code="$?"
if [ "$code" -gt "$EXIT" ]; then EXIT="$code"; fi # collect exit code

if [ "$EXIT" -ne 0 ]; then exit "$EXIT"; fi # exit with highest exit code

