#!/bin/bash
#SBATCH --partition=main
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --mem=10G
#SBATCH --time=1:30:00
#SBATCH -o /miniscratch/gillonco/losses_%j.txt

# 1. Set directory in which to load and plot results (also update output directory above)
SAVE_DIR=/miniscratch/gillonco

if [[ ! -d $SAVE_DIR ]]; then
    echo -e "Save directory '$SAVE_DIR' does not exist. Please set SAVE_DIR "\
            "to the path of an existing directory."
    exit 1
fi


# 2. Load modules
module purge
module load anaconda/3
module load cuda/10.2/cudnn/7.6

conda activate ssl


# 3. Launch your job
python plot_losses.py --direc $SAVE_DIR/test_gabors

