#!/bin/bash
#SBATCH --qos=high                      # Ask for unkillable job
#SBATCH --cpus-per-task=1                     # Ask for 1 CPUs
#SBATCH --gres=gpu:2                          # Ask for 1 GPU
#SBATCH --mem=10G                             # Ask for 10 GB of RAM
#SBATCH --time=1:00:00                        # The job will run for 3 hours
#SBATCH -o /network/tmp1/wilmeska/slurm-%j.out  # Write the log on tmp1

module purge
module load anaconda/3
source $CONDA_ACTIVATE

# 1. Load your environment
conda activate $HOME/cn-dpc/condaenv-dpc/

# 2. Copy your dataset on the compute node
#cp $HOME/DenseCPC/UCF101.zip $SLURM_TMPDIR
#unzip -q $SLURM_TMPDIR/UCF101.zip -d $SLURM_TMPDIR
#cd ./process_data/src
#python write_csv.py

# 2. Copy pre-trained model to SLURM_TMPDIR
cp /network/home/wilmeska/DenseCPC/k400_128_r18_dpc-rnn.pth.tar $SLURM_TMPDIR/
# 3. Launch your job, tell it to save the model in $SLURM_TMPDIR
#    and look for the dataset into $SLURM_TMPDIR
#cd ../../eval
echo 'copied pretrained net'

cd ./dpc
python test_gabors.py --gpu 0,1 --net resnet18 --dataset gabors --batch_size 10 --num_seq 10 --seq_len 4 --img_dim 128 --pretrain {$SLURM_TMPDIR/k400_128_r18_dpc-rnn.pth.tar} --train_what ft --epochs 100

# 4. Copy whatever you want to save on $SCRATCH
#cp -r $SLURM_TMPDIR/loss.yaml /network/tmp1/wilmeska/
#cp -r $SLURM_TMPDIR/seq.yaml /network/tmp1/wilmeska/

